version: "3.8"

services:
  app:
    image: ghcr.io/korjavin/fastfooddb:bdc2fbd5539f1ce2f200ae51f0ea097af3585f00
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DATA_DIR=${DATA_DIR:-/app/data}
      - API_KEYS=${API_KEYS}
    volumes:
      - ./data:/app/data
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastfooddb.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.fastfooddb.tls=true"
      - "traefik.http.routers.fastfooddb.tls.certresolver=myresolver"
      - "traefik.http.services.fastfooddb.loadbalancer.server.port=8080"

networks:
  traefik_network:
    name: ${NETWORK_NAME:-traefik_network}
    external: true
